### ISSUE TITLE
Error on installation : undefined : strings.ReplaceAll

### ISSUE THREAD

**Issue by arcteezy** [northwesternmutual/grammes#10]
I just ran the installation command in the terminal.

> go get -u github.com/northwesternmutual/grammes

It resulted in the following error.

> github.com/northwesternmutual/grammes/query/traversal
> ../../github.com/northwesternmutual/grammes/query/traversal/addproperty.go:54:24: undefined: strings.ReplaceAll
> ../../github.com/northwesternmutual/grammes/query/traversal/addproperty.go:63:26: undefined: strings.ReplaceAll

**Comment by damienfamed75** [comment]
Grammes requires go 1.12+

strings.ReplaceAll was added in Go 1.12

**Comment by arcteezy** [comment]
Upgraded Go to 1.13. Works fine.
