### ISSUE TITLE
errors not returned

### ISSUE THREAD

**Issue by blackjune** [northwesternmutual/grammes#6]
[https://github.com/northwesternmutual/grammes/blob/master/response.go#L78](url)

**Comment by damienfamed75** [comment]
@blackjune do you mind explaining your issue? From what I can see the error is being returned.
The loop on response.go#L77 looks fine to me.

```go
for _, d := range dataI.([]interface{}) {
	if dataPart, err = jsonMarshalData(d); err != nil {
		return nil, err // L78: being returned
	}

	data = append(data, dataPart)
}
```

**Comment by blackjune** [comment]
when d is an error, d will be lost

**Comment by damienfamed75** [comment]
Hmmm... I see.

Do you mind making a pull request with those changes?
