### ISSUE TITLE
Failed to execute example add-vertex-by-query

### ISSUE THREAD

**Issue by posilva** [northwesternmutual/grammes#8]
When I try to execute this example I am getting this error:

> json: cannot unmarshal string into Go struct field VertexValue.@value.id of type model.ID}

The json generated is this: 

``` json
{
    "@type": "g:List",
    "@value": [
        {
            "@type": "g:Vertex",
            "@value": {
                "id": "78b774f6-e7a0-26bf-2fb8-fb25d413aea5",
                "label": "person",
                "properties": {
                    "name": [
                        {
                            "@type": "g:VertexProperty",
                            "@value": {
                                "id": {
                                    "@type": "g:Int32",
                                    "@value": 1032144519
                                },
                                "label": "name",
                                "value": "damien"
                            }
                        }
                    ]
                }
            }
        }
    ]
}

```

Looking at the code the VertexValue struct has an ID that does not support String but instead a struct 

```go

type ID struct {
Type  string `json:"@type"`
	Value int64  `jjson:"@value"`
}
```

That's why the error, not able to convert the ID: "78b774f6-e7a0-26bf-2fb8-fb25d413aea5" to the mentioned struct.

I am using version grammes v1.1.1

**Comment by damienfamed75** [comment]
What database are you using?
What are the steps used to recreate this?

**Comment by posilva** [comment]
I am using AWS Neptune. Just notice one issue closed, that reports the same error. 
Closing this one
